GET http://127.0.0.1:8000/api/events
Content-Type: application/json
Accept: application/json
# Authorization: eyJpdiI6InBjUW9EMlhTRVFzakorUDltMi93UVE9PSIsInZhbHVlIjoiM0ZEakVqb2pUN1l0aHpLcnlJQlZJT05EeHFDVy9OcFdNMk5BRHlGU1A4aFJac0pINGVhZVBxZi9tTlV4VU1UVjNmQmJlOHZPWHJoWnRMa0J4VnVSeFFFd3E0Tnc0UFNGdC9iVFBjS1IvVzFIUTJkMkkvSWxSTkdRODU5RzdsdzUiLCJtYWMiOiI5N2E3OWY2NzdkZGNmYjc4ZmRlY2ZkNmRiNWM2MzA3Y2Q4NGU3NzhmNzIxNjI5ODk2Y2FiMmViY2IzODU3OGU4IiwidGFnIjoiIn0=
